name: Tests

on:
  push:
    branches: [package, master]
  pull_request:
    branches: [package, master]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install .[dev,postgres]
      - name: Run tests
        run: |
          coverage run -m pytest --postgresql-password=postgres --postgresql-host=postgres
      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}